// <auto-generated> Run: dotnet run --project tools/SkillIdGenerator -- generate
// Source of truth: tools/skill-id-registry.json

public enum SkillID
{
    None = -1,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    Determination = 0,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    ReNewedSpirit = 1,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    TerminateLight = 2,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    Smite = 3,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    Charge = 4,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    SacredOnslaught = 5,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    ResonantSlash = 6,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    EchoPuncture = 7,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    BreakStrike = 8,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    EchonicResonance = 9,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    SonicBoom = 10,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    PhaseEcho = 11,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    SoundBarrier = 12,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    SonicDeflection = 13,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    TuningStance = 14,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    ResonantWard = 15,
    EvilAttack = 16,
    EvilSurvive = 17,
    EvilTermin = 18,
    DeSurviveSkill = 19,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    ShockWave = 20,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    AbsouluteDefense = 21,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    TauntingGuard = 22,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    HolySeal = 23,
    FearWormAttack = 24,
    FearWormSurvive = 25,
    FearWormTermin = 26,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    MendSlash = 27,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    FinalGuard = 28,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    RebirthPrayer = 29,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    ShadowAmbush = 30,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    ShadowExecution = 31,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    VeilStep = 32,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    TempoSurge = 33,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    Sacrifice = 34,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    LongNight = 35,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    Vower = 36,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    FlashOfLight = 37,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    CrystalGuard = 38,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    Swift = 39,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    StarWard = 40,
    ArmonAttack = 41,
    ArmonSurvive = 42,
    ArmonSpecial = 43,
    ArroganceAttack = 44,
    ArroganceSurvive = 45,
    ArroganceSpecial = 46,
    AlienBodyAttack = 47,
    AlienBodySurvive = 48,
    AlienBodySpecial = 49,
    RedHuskAttack = 50,
    RedHuskSurvive = 51,
    RedHuskSpecial = 52,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    SwapSlash = 53,
    WarAttack = 54,
    WarSurvive = 55,
    WarSpecial = 56,
    WarThrallAttack = 57,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    QuietVeil = 58,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    SiphonSlash = 59,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    ShatterSlash = 60,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    EnergyTransfer = 61,
    FerociouessAttack = 62,
    FerociouessSurvive = 63,
    FerociouessSpecial = 64,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    StasisBlade = 65,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    RequiemBloom = 66,
    TurbineAttack = 67,
    TurbineSurvive = 68,
    TurbineSpecial = 69,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    AegisPledge = 70,
    BasicAttack = 71,
    BasicDefense = 72,
    BasicSpecial = 73,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    DissonantField = 74,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    ReverbChain = 75,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    VulnerablePurge = 76,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    VulnerabilityStrike = 77,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    VulnerabilityConversion = 78,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    TwilightParadox = 79,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    RearlineRevival = 80,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    EnergyRelay = 81,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    WeakpointBulwark = 82,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    GroupHealing = 83,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    AfterimageWard = 84,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    BarrierDuplication = 85,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    RelayShift = 86,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    ContinuousPierce = 87,
    BlackHawkAttack = 88,
    BlackHawkSurvive = 89,
    BlackHawkSpecial = 90,
    InexorabilityAttack = 91,
    InexorabilitySurvive = 92,
    InexorabilitySpecial = 93,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    DisasterImpact = 94,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    TouchOfGod = 95,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    Ragnarok = 96,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    BladeOfSlaughter = 97,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    Extract = 98,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    ShadowForm = 99,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    DemonForm = 100,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    VoidForm = 101,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    EchoForm = 102,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    SanctuaryForm = 103,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    ChargedBlade = 104,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    RuinBlade = 105,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    CurtainCallMoment = 106,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    CrescentWind = 107,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    ResonanceShelter = 108,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    WarGodWill = 109,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    SunMoonCycle = 110,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    ConcordSlash = 111,
    BasicGuard = 112,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    NightingaleEnergy = 113,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    ReadyStance = 114,
    GraveWraithAttack = 115,
    GraveWraithSurvive = 116,
    GraveWraithSpecial = 117,
    DeathAttack = 118,
    DeathSurvive = 119,
    DeathSpecial = 120,
    VoidAcolyteAttack = 121,
    VoidAcolyteSurvive = 122,
    VoidAcolyteSpecial = 123,
    VoidStatus = 124,
    HollowBulwarkAttack = 125,
    HollowBulwarkSurvive = 126,
    HollowBulwarkSpecial = 127,
    MarrowReaverAttack = 128,
    MarrowReaverSurvive = 129,
    MarrowReaverSpecial = 130,
    WoundStatus = 131,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    Purity = 132,
    DazeStatus = 133,
    VoidRotorAttack = 134,
    VoidRotorSurvive = 135,
    VoidRotorSpecial = 136,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    BrightestMoment = 137,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    EternalDark = 138,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    HopeBeacon = 139,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    CursePower = 140,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    WeakeningField = 141,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    StillWaterMirror = 142,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    DeflectionShield = 143,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    Purification = 144,
    AngerEliteAttack = 145,
    AngerEliteSurvive = 146,
    AngerEliteSpecial = 147,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    HolyOfHolies = 148,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    TacticalPreparation = 149,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    RadiantOverload = 150,
    FearEliteAttack = 151,
    FearEliteSurvive = 152,
    FearEliteSpecial = 153,
    PlagueStatus = 154,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    EternalCore = 155,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    NightfallFlurry = 156,
    EnvyEliteAttack = 157,
    EnvyEliteSurvive = 158,
    EnvyEliteSpecial = 159,
    HavocAttack = 160,
    HavocSurvive = 161,
    HavocSpecial = 162,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    KasiyaBasicSpecial = 163,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    EchoBasicSpecial = 164,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    MariyaBasicSpecial = 165,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    NightingaleBasicSpecial = 166,
    [ColorlessSkill]
    Blade = 167,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    BladeSalvo = 168,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    ExhaustBulwark = 169,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    Resistance = 170,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    Foresight = 171,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    BladeDance = 172,
    [ColorlessSkill]
    Calmness = 173,
    [ColorlessSkill]
    DefenceFocus = 174,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    RenewalFlurry = 175,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    SoundPickup = 176,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    LingeringTone = 177,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    WardGift = 178,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    ShadowBladeWard = 179,
    [PlayerSkill(PlayerCharacterKey.Echo)]
    Overdraw = 180,
    [PlayerSkill(PlayerCharacterKey.Kasiya)]
    Recycling = 181,
    [PlayerSkill(PlayerCharacterKey.Mariya)]
    Prediction = 182,
    [PlayerSkill(PlayerCharacterKey.Nightingale)]
    Search = 183,
}
